spring:
  application:
    name: hospital-service
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    hospital.management.system: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/hospital-service.log
    max-size: 10MB
    max-history: 30

