server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:


        - id: hospital-service
          uri: lb://hospital-service
          predicates:
            - Path=/hospital/**
          filters:
            - StripPrefix=1


        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2


        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true


  swagger-ui:
    enabled: true
    urlsPrimaryName: hospital-service

    urls:
       - name: hospital-service
         url: http://localhost:8080/hospital/v3/api-docs

       - name: user-service
         url: http://localhost:8080/api/auth/v3/api-docs

       - name: admin-service
         url: http://localhost:8080/api/admin/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG